### PR TITLE
Adding a package.json file for distribution through npm

### PR DESCRIPTION
**Pull request by bcjwilson**
Hoping to use video.js-component for distribution of video.js assets through npm.

### CODE REVIEW

**Comment by heff** [comment]
Nice. Do you want to update the lib to 4.1.0 too? It's currently out of date in this repo.

**Comment by bcjwilson** [comment]
I didin't realize it was out of date, I was just adding the package.json - what do you recommend?

**Comment by bcjwilson** [comment]
What's the procedure for updating this?

**Comment by heff** [comment]
Just copying the latest files from videojs.com into this repo.

**Comment by bcjwilson** [comment]
Done and done

**Comment by heff** [comment]
and done

**Comment by bcjwilson** [comment]
Thanks!

**Pull request merged**
