### PR TITLE
Updated to video.js 4.5.1

### PR DESCRIPTION
**Pull request by ItsBenCodes**

### CODE REVIEW

**Comment by gkatsev** [comment]
vjs 4.5.1 should be available from bower. We're moving to have things served from the main repo so eventually this repo won't be needed. We just need to update the meta data in bower.

**Comment by ItsBenCodes** [comment]
Unless you commit the dist folder in the main repo (which is undesirable), their is no way you can use it as the bower git

**Comment by ItsBenCodes** [comment]
Just saw grunt bump. Is it what video.js is planning to implement?

**Comment by heff** [comment]
Try `bower videojs` as opposed to `bower video.js`. The former points to the main repo and should work as expected. We really need to clean this up.

@gkatsev, could we kill the -component version now?

**Pull request closed without merging**
