### PR TITLE
Video.css no longer exists so Bower install breaks

### PR DESCRIPTION
**Pull request by qbunt**
Just updated the bower.json file so it works with the new css file name.

### CODE REVIEW

**Comment by heff** [comment]
Thanks, pulling in. This video.js-component has actually been deprecated and the main video.js repo should be used. There's a `video.js` and a `videojs` in the bower directory, and one of those needs to be killed.

**Comment by qbunt** [comment]
Sweet, thanks @heff

**Comment by qbunt** [comment]
Requested removal of `video.js` in https://github.com/bower/bower/issues/120 . I'll update this issue if it gets cleared out so it can be re-registered.

**Comment by heff** [comment]
Awesome, thanks!

**Comment by desandro** [comment]
Unregistered!

**Comment by qbunt** [comment]
I'm going to re-register video.js with the new the central git://github.com/videojs/video.js.git. That sound alright to you guys?

**Comment by heff** [comment]
Does it matter if there's two bower names for the same repo?

**Comment by qbunt** [comment]
This would definitely not be the first time I've seen that. Because there's existing things pointing to `video.js` in this case, it makes some level of sense. Thoughts?

**Comment by heff** [comment]
Yeah, I don't see any specific issues with that, as long as they continue to work the same without any extra work to keep them both updated.

**Pull request merged**
