### PR TITLE
Add component.json and main script exports

### PR DESCRIPTION
**Pull request by peteschaffner**
Your README claims support for `component(1)` ... lets make it happen ;)

### CODE REVIEW

**Comment by peteschaffner** [comment]
Reading #4 and realized the changes to `video.js` in this PR prolly won't fly. It would be nice though, to add `exports` support for CommonJS `require()` implementations (i.e. [`browserify`](https://github.com/substack/node-browserify), [`component`](https://github.com/component/component), [`gluejs`](https://github.com/mixu/gluejs), etc.).

**Comment by heff** [comment]
Yeah, we would need to build something into video.js itself to make this work long term. On the video.js swf repo we've move to just including the compiled files in the repo, and we'll probably do the same with video.js. I was looking into browserfy recently and it looked like it had some good options for generating versions that support the different module loaders. Want to see what it'd look like to add browserfy to video.js to build those versions?

**Comment by peteschaffner** [comment]
Yeah totally, I will look into it. I agree we should be module-style agnostic about it (though for me its CommonJS or gtfo haha). Anyway, I will see what browserify offers in terms of automating this ... or maybe we just do something similar to what [Backbone](https://github.com/jashkenas/backbone/blob/master/backbone.js#L11) and [Underscore](https://github.com/jashkenas/underscore/blob/master/underscore.js#L54) are doing.

**Comment by gkatsev** [comment]
Just remember that you need to check `exports` for commonjs-like _before_ checking for amd's define.

**Comment by peteschaffner** [comment]
@heff It looks like browserify option you mentioned comes from this [`umd` wrapper](https://github.com/ForbesLindesay/umd). We could definitely use that, but since you are using `grunt` for building, maybe it would be better to use [this pre-made task](https://github.com/alexlawrence/grunt-umd).

@gkatsev both of these wrappers check for `exports` first, yet the official `umd` project seems to [suggest the opposite](https://github.com/umdjs/umd/blob/master/returnExports.js#L18)? :\

I'm opening a PR for this, yet ultimately it will be dependent on [#874](https://github.com/videojs/video.js/pull/874) getting merged and then adding build files to the repo. I've only added the `umd` tasks for now as I need to grok your build/minify tasks. Lets move the convo [over there](https://github.com/videojs/video.js/pull/990)?

**Comment by gkatsev** [comment]
Yeah, the "official" umd wrapper is wrong :)

**Comment by peteschaffner** [comment]
Haha. Good to know!

**Pull request closed without merging**
